### ISSUE TITLE
Change current installation version

### ISSUE THREAD

**Issue by rdig** [rdig/wpa-cli#7]
Be able to change the version of the current wordpress install.

This is useful for backwards compatibility testing.

It shouldn't be to hard to implement since it's basically an update, but with another version tag.

An outline on what should be done _(not limited to these)_:
- [ ] create a function that lists all the available versions (_tags_)
- [ ] create a function that takes in a version string, parses & validates it, checks if it's an available release
- [ ] modify the [install() method]() to get the version from a passed in argument (_the previous mentioned version parsing function_), otherwise revert to the default functionality _(latest tag release)_

**Comment by rdig** [comment]
- [ ] create a function that takes in a version string, parses & validates it, checks if it's an available release
- [ ] modify the [update() method](https://github.com/rdig/wpa-cli/blob/master/includes/wpa.js#L146) to get version from a passed argument, otherwise revert to the default functionality *(latest tag release)*
